# These are supported funding model platforms

#github: [admpub]
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CEZMMPLT83DK4', 'https://b.webx.top/donation/wechat', 'https://b.webx.top/donation/alipay','https://afdian.net/a/nging']
