ports:
  - port: 8080
    onOpen: open-preview
  - port: 5001-5050
    onOpen: ignore
tasks:
  - init:  |
      cd /workspace && go install github.com/webx-top/tower@latest
    command: |
      cd /workspace/nging
      go mod vendor
      tower
