# brew install pre-commit
# pre-commit install
repos:
- repo: git@github.com:go-coscms/pre-commit-golang
  rev: v0.3.6
  hooks:
  #  - id: go-fmt
  #  - id: go-vet
  #  - id: go-lint
    - id: go-imports
  #  - id: go-cyclo
  #    args: [-over=15]
  #  - id: validate-toml
  #  - id: no-go-testing
  #  - id: gometalinter
  #  - id: golangci-lint
  #  - id: go-critic
  #  - id: go-unit-tests
  #  - id: go-build
    - id: go-mod-tidy
