# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: GOPATH=/home/runner/go mkdir -p $GOPATH/src/github.com/admpub/ && ln -s "$(pwd)" $GOPATH/src/github.com/admpub/nging && go mod vendor && cd ./tool/nging-builder && ./run.sh linux_amd64 && cd ../../
      env:
        GOPATH: /home/runner/go

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "admpub/nging:latest"
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    # - name: Test
    #   run: go test -v ./...
