# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ReleaseDockerImage

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:

  build:
    if: github.repository == 'admpub/nging'
    runs-on: ubuntu-latest
    # container:
    #   image: admpub/xgo:1.21.6
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'

    - name: Build
      run: mkdir -p "$GOPATH/src/github.com/admpub" && ln -s "$(pwd)" "$GOPATH/src/github.com/admpub/nging" && go mod vendor && cd ./tool/nging-builder && go install github.com/admpub/xgo@latest && ./run.sh linux_amd64 && cd ../../
      env:
       GOPATH: /home/runner/go

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "admpub/nging:latest" --build-arg VERSION=$(grep NgingVersion ./tool/nging-builder/builder.conf | sed 's/NgingVersion[ ]*:[ ]*//g' | sed 's/"//g' | sed 's/ //g') && docker push admpub/nging:latest
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    # - name: Test
    #   run: go test -v ./...
